companies_dict = {
    "Apple": "AAPL",
    "NVIDIA": "NVDA",
    "Microsoft": "MSFT",
    "Alphabet (Google)": "GOOGL",
    "Amazon": "AMZN",
    "Meta Platforms (Facebook)": "META",
    "Berkshire Hathaway": "BRK.B",
    "Tesla": "TSLA",
    "Broadcom": "AVGO",
    "Eli Lilly": "LLY",
    "Walmart": "WMT",
    "JPMorgan Chase": "JPM",
    "Visa": "V",
    "Exxon Mobil": "XOM",
    "UnitedHealth": "UNH",
    "Oracle": "ORCL",
    "Mastercard": "MA",
    "Costco": "COST",
    "Procter & Gamble": "PG",
    "Home Depot": "HD",
    "Johnson & Johnson": "JNJ",
    "AbbVie": "ABBV",
    "Netflix": "NFLX",
    "Bank of America": "BAC",
    "Coca-Cola": "KO",
    "Salesforce": "CRM",
    "Chevron": "CVX",
    "Merck": "MRK",
    "T-Mobile US": "TMUS",
    "AMD": "AMD",
    "PepsiCo": "PEP",
    "Cisco": "CSCO",
    "Wells Fargo": "WFC",
    "Thermo Fisher Scientific": "TMO",
    "Adobe": "ADBE",
    "IBM": "IBM",
    "McDonald's": "MCD",
    "Philip Morris": "PM",
    "Abbott Laboratories": "ABT",
    "General Electric": "GE",
    "QUALCOMM": "QCOM",
    "American Express": "AXP",
    "Texas Instruments": "TXN",
    "Morgan Stanley": "MS",
    "Caterpillar": "CAT",
    "Danaher": "DHR",
    "Intuitive Surgical": "ISRG",
    "Verizon": "VZ",
    "Walt Disney": "DIS",
    "Intel": "INTC",
    "AT&T": "T",
    "Pfizer": "PFE",
    "Boeing": "BA",
    "Comcast": "CMCSA",
    "Union Pacific": "UNP",
    "UPS": "UPS",
    "CVS Health": "CVS",
    "Goldman Sachs": "GS",
    "Honeywell": "HON",
    "3M": "MMM",
    "Medtronic": "MDT",
    "Nike": "NKE",
    "Lockheed Martin": "LMT",
    "Altria Group": "MO",
    "Colgate-Palmolive": "CL",
    "ConocoPhillips": "COP",
    "Deere & Company": "DE",
    "NextEra Energy": "NEE",
    "General Motors": "GM",
    "Ford Motor Company": "F",
    "Starbucks": "SBUX",
    "eBay": "EBAY",
    "Kraft Heinz": "KHC",
    "Mondelez International": "MDLZ",
    "PayPal": "PYPL",
    "Bristol-Myers Squibb": "BMY",
    "Dow Inc.": "DOW",
    "AIG": "AIG",
    "Citigroup": "C",
    "Travelers Companies": "TRV",
    "DuPont": "DD",
    "Gilead Sciences": "GILD",
    "Dominion Energy": "D",
    "Southern Company": "SO",
    "Raytheon Technologies": "RTX",
    "BlackRock": "BLK",
    "Charles Schwab": "SCHW",
    "Booking Holdings": "BKNG",
    "Target Corporation": "TGT",
    "Biogen": "BIIB",
    "Prudential Financial": "PRU",
    "Delta Air Lines": "DAL",
    "American Airlines": "AAL",
    "Southwest Airlines": "LUV",
    "Capital One": "COF",
    "PNC Financial Services": "PNC",
    "Progressive Corporation": "PGR",
    "Linde plc": "LIN",
    "S&P Global": "SPGI",
    "Elevance Health (formerly Anthem)": "ELV",
    "Boston Scientific": "BSX",
    "Micron Technology": "MU",
    "Applied Materials": "AMAT",
    "HP Inc.": "HPQ",
    "Hewlett Packard Enterprise": "HPE",
    "Seagate Technology": "STX"
}

market_indicators = [
    "inflation",
    "interest rates",
    "gross domestic product",
    "gdp",
    "unemployment rate",
    "consumer confidence index",
    "consumer confidence",
    "purchasing managers' index",
    "pmi",
    "consumer price index",
    "cpi",
    "producer price index",
    "ppi",
    "housing starts",
    "housing market",
    "retail sales",
    "industrial production",
    "federal funds rate",
    "fed rate",
    "bond yields",
    "stock market",
    "volatility index",
    "vix",
    "volatility",
    "money supply",
    "commodity prices",
    "trade balance",
    "business inventories",
    "inventory levels",
    "capacity utilization",
    "durable goods orders",
    "jobless claims",
    "initial jobless claims",
    "manufacturing activity",
    "manufacturing",
    "employment figures",
    "employment numbers",
    "core inflation",
    "personal consumption expenditures",
    "consumer spending",
    "business investment",
    "government spending",
    "budget deficit",
    "exchange rates",
    "balance of payments",
    "current account",
    "leading economic indicators",
    "economic indicators",
    "credit growth",
    "debt levels",
    "savings rate",
    "capital flows",
    "economic sentiment",
    "labor force participation rate",
    "labor force participation",
    "income growth",
    "wages",
    "productivity",
    "fiscal policy",
    "monetary policy",
    "corporate earnings",
    "liquidity",
    "default rates",
    "trade policy",
    "economic sanctions",
    "wage growth",
    "bull market",
    "bear market",
    "market rally",
    "market correction",
    "economic downturn",
    "recession",
    "economic boom",
    "consumer debt",
    "credit crunch",
    "housing bubble",
    "yield curve",
    "rate hike",
    "interest rate hike",
    "quantitative easing",
    "qe",
    "tapering",
    "financial stability",
    "market volatility",
    "market crash",
    "growth rate",
    "household income",
    "job growth",
    "interest rate cut",
    "stimulus package",
    "trade deficit",
    "foreign exchange",
    "forex",
    "market sentiment",
    "market optimism",
    "market pessimism",
    "recovery",
    "economic slowdown",
    "real estate market",
    "housing prices",
    "foreclosures",
    "consumer loans",
    "personal savings",
    "investment spending",
    "credit score",
    "income inequality"
]




important_subreddits = [
    "stocks",
    "stockmarket",
    "wallstreetbets",
    "options",
    "thetagang",
    "smallstreetbets",
]