companies_dict = {
    "Apple": "AAPL",
    "NVIDIA": "NVDA",
    "Microsoft": "MSFT",
    "Alphabet (Google)": "GOOGL",
    "Amazon": "AMZN",
    "Meta Platforms (Facebook)": "META",
    "Berkshire Hathaway": "BRK.B",
    "Tesla": "TSLA",
    "Broadcom": "AVGO",
    "Eli Lilly": "LLY",
    "Walmart": "WMT",
    "JPMorgan Chase": "JPM",
    "Visa": "V",
    "Exxon Mobil": "XOM",
    "UnitedHealth": "UNH",
    "Oracle": "ORCL",
    "Mastercard": "MA",
    "Costco": "COST",
    "Procter & Gamble": "PG",
    "Home Depot": "HD",
    "Johnson & Johnson": "JNJ",
    "AbbVie": "ABBV",
    "Netflix": "NFLX",
    "Bank of America": "BAC",
    "Coca-Cola": "KO",
    "Salesforce": "CRM",
    "Chevron": "CVX",
    "Merck": "MRK",
    "T-Mobile US": "TMUS",
    "AMD": "AMD",
    "Pepsico": "PEP",
    "Cisco": "CSCO",
    "Wells Fargo": "WFC",
    "Thermo Fisher Scientific": "TMO",
    "Adobe": "ADBE",
    "IBM": "IBM",
    "McDonald": "MCD",
    "Philip Morris": "PM",
    "Abbott Laboratories": "ABT",
    "ServiceNow": "NOW",
    "General Electric": "GE",
    "QUALCOMM": "QCOM",
    "American Express": "AXP",
    "Texas Instruments": "TXN",
    "Morgan Stanley": "MS",
    "Caterpillar": "CAT",
    "Danaher": "DHR",
    "Intuitive Surgical": "ISRG",
    "Verizon": "VZ",
    "Walt Disney": "DIS"
}

important_subreddits = [
    "stocks",
    "stockmarket",
    "wallstreetbets",
    "options",
    "thetagang",
    "smallstreetbets",
]