companies_dict = {
    "Apple": "AAPL",
    "NVIDIA": "NVDA",
    "Microsoft": "MSFT",
    "Alphabet (Google)": "GOOGL",
    "Amazon": "AMZN",
    "Meta Platforms (Facebook)": "META",
    "Berkshire Hathaway": "BRK.B",
    "Tesla": "TSLA",
    "Walmart": "WMT",
    "JPMorgan Chase & Co.": "JPM",
    "Netflix": "NFLX",
    "Bank of America": "BAC",
    "Salesforce, Inc.": "CRM",
    "AMD": "AMD",
    "Thermo Fisher Scientific": "TMO",
    "IBM": "IBM",
    "Philip Morris International": "PM",
    "The Walt Disney Company": "DIS",
    "Intel": "INTC",
    "Pfizer": "PFE",
    "Boeing": "BA",
    "UPS": "UPS",
    "Goldman Sachs": "GS",
    "3M": "MMM",
    "Deere & Company": "DE",
    "Starbucks Corporation": "SBUX",
    "PayPal": "PYPL",
    "Dow Inc.": "DOW",
    "American International Group": "AIG",
    "BlackRock": "BLK",
    "Target Corporation": "TGT",
    "American Airlines Group": "AAL",
    "HP Inc.": "HPQ"
}

market_indicators = [
    "inflation",
    "deflation",
    "gdp",
    "cpi",
    "vix",
    "bull market",
    "bear market",
    "recession",
    "recovery",
    "crash",
    "bubble"
]

important_subreddits = [
    "stocks",
    "stockmarket",
    "wallstreetbets",
    "options",
    "thetagang",
    "smallstreetbets",
    "StocksAndTrading"
    "AAPL",
    "NvidiaStock",
    "NVDA_Stock",
    "brkb",
    "tsla",
    "tslaLounge",
    "teslainvestorsclub"
]